Add anonymized Jira Inquiries
onc-healthit/api-resource-guide pull request #26
Opened 2022-09-07 17:30 UTC by imkacarlson

This includes 2 new pages where we can publish anonymized 170.315(g)(10) and 170.404 inquiries in their own respective pages.

Links to these new pages have been added to the (g)(10) and 404 home pages:

**Link on (g)(10) homepage**:
![image](https://user-images.githubusercontent.com/31493326/188941776-de5c1582-330a-4c07-ad1a-ad2c6df7a2a1.png)

**Link on 170.404 homepage**:
![image](https://user-images.githubusercontent.com/31493326/188941942-abeaac2a-1b1c-4ce2-af92-43d0dd938269.png)

Then those new links take you to a page with the anonymized inquiries:
![image](https://user-images.githubusercontent.com/31493326/188942111-4f89d824-35b0-4261-a126-661189f32cbb.png)

2022-09-08 20:06 UTC, scottbohon commented on docs/inquiry-portal/g10-inquiries.md
> +[1] Health IT Modules may use access control schemes other than OAuth 2.0 for controlling access to the file server, such as capability URLs. The HL7 FHIR-I Work Group has documented expectations for
Consider having the clarification in italics.

2022-09-08 20:15 UTC, scottbohon commented on docs/inquiry-portal/g10-inquiries.md
> +Beyond the certification criteria requirements, health IT developers are not required to support all methods that third-party application developers seek to use. Additional information and clarificat
Review the sentence "Additional information and clarifications regarding this criterion can be found on the <a target = "_blank" href = "https://www.healthit.gov/test-method/standardized-api-patient-and-population-services#ccg">September</a>." "September" should likely instead be "(g)(10) CCG".

2022-09-08 20:16 UTC, scottbohon commented on docs/inquiry-portal/g10-inquiries.md
> +The  FHIR specification says that there should be alternatives: https://hl7.org/fhir/uv/bulkdata/export/index.html#response---complete-status
Consider making a clickable hyperlink.

2022-09-08 20:16 UTC, scottbohon commented on docs/inquiry-portal/g10-inquiries.md
> +**Stakeholder Inquiry**: If we certify to 170.315(g)(10), does that cover all of the API requirements specified in this PDF? https://www.healthit.gov/cures/sites/default/files/cures/2020-03/APICertif
Consider making a clickable hyperlink.

2022-09-08 20:18 UTC, scottbohon commented on docs/inquiry-portal/g10-inquiries.md
> +**ONC Response**: According to the regulation text for the 170.315(g)(10) certification criterion at 45 CFR 170.315(g)(10)(i )(A), health IT developers must demonstrate the ability of Health IT Modul
Consider replacing "(i )" with "(i)", removing the space.

2022-09-08 20:21 UTC, scottbohon commented on docs/inquiry-portal/g10-inquiries.md
> +**Stakeholder Inquiry**: Does ONC have a published list of IP addresses we can whitelist for the (g)(10) Standardized API Test Kit hosted at https://inferno.healthit.gov/onc-certification-g10-test-ki
Consider making a clickable hyperlink.

2022-09-08 20:26 UTC, scottbohon commented on docs/inquiry-portal/404-inquiries.md
> +**Stakeholder Inquiry**: According to the 21st Century Cures Act: Interoperability, Information Blocking, and the ONC Health IT Certification Program Final Rule (ONC Cures Act Final Rule) timeline, O
Consider putting "made available" in quotes in the last sentence.

2022-09-08 20:29 UTC, scottbohon commented on docs/inquiry-portal/404-inquiries.md
> +If a health IT developer currently has Health IT Modules certified to 45 CFR 170.315(g)(8) under the ONC Health IT Certification Program, it must meet this Maintenance of Certification requirement no
Consider a clickable link for "http://www.healthit.gov/Direct-Review"

2022-09-08 20:30 UTC, scottbohon requested changes
I added comments for your consideration.

2022-09-09 13:06 UTC, imkacarlson commented
Thanks Scott!

Made updates based off your suggestions.

Also added links to the corresponding inquiry sections on the Information and Clarifications pages:

![image](https://user-images.githubusercontent.com/31493326/189356577-5b08665f-b088-4ae7-abdf-6b344d1f4622.png)

2022-09-09 14:24 UTC, scottbohon commented on docs/inquiry-portal/g10-inquiries.md
> +The ONC Certification criteria for eCQMs does not require any FHIR standards. For additional information on CMS regulations, please reference CMS sources or contact CMS if you have questions about sp
Consider clickable links for links in this paragraph.

2022-09-09 14:30 UTC, scottbohon reviewed
Made a comment for your consideration.

2022-09-09 18:57 UTC, merged